framework:
  asset_mapper:
    # The paths to make available to the asset mapper.
    paths:
      - assets/
    excluded_patterns:
      - "assets/styles/_*.css"
    server: true

when@prod:
  framework:
    asset_mapper:
      missing_import_mode: warn
